# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ListenNovel' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ListenNovel

  target 'ListenNovelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListenNovelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
